name: actions-metrics-otlp
description: capture github actions metrics

inputs:
  github-token:
    description: GitHub token to get jobs and steps if needed
    default: ${{ github.token }}
    required: true
  github-token-rate-limit-metrics:
    description: GitHub token for rate limit metrics
    default: ${{ github.token }}
    required: true

  collect-job-metrics:
    description: Collect job metrics
    required: false
    default: 'false'
  collect-step-metrics:
    description: Collect step metrics
    required: false
    default: 'false'
  send-pull-request-labels:
    description: Send pull request labels as Datadog tags
    required: false
    default: 'false'

  gcp-project-id:
    description: GCP Project ID
    required: false
    default: ''
  use-console-exporter:
    description: Override exporter and export only to ocnsole
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
